# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0002_drink_event_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='post_date',
        ),
    ]
