# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 03:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0003_remove_rating_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 4, 3, 1, 56, 922195, tzinfo=utc)),
        ),
    ]
