# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0005_auto_20171204_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
