# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0006_auto_20171204_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='drink_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='drink_id',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
