# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0010_auto_20171204_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(default=1, height_field=100, upload_to='', width_field=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
