# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0011_auto_20171207_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='', width_field=100),
        ),
    ]
