# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0013_auto_20171207_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_choices',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=20),
        ),
    ]
