# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0015_auto_20171210_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
