# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0020_auto_20171210_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='drink_id',
        ),
    ]
