# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0021_remove_rating_drink_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='drink_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drinkproj.Drink'),
            preserve_default=False,
        ),
    ]
