# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0022_rating_drink_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_lineup',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='event_lineup',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='drink_id',
            new_name='drink',
        ),
    ]
