# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0024_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating_choices',
            new_name='rating',
        ),
    ]
