# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0025_auto_20180107_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='', width_field='image_width'),
        ),
    ]
