# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0029_auto_20180109_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='url_height',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='url_width',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, height_field='url_height', null=True, upload_to='', width_field='url_width'),
        ),
    ]
