# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 19:46
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0030_auto_20180109_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, height_field='url_height', null=True, upload_to='', width_field='url_width'),
        ),
    ]
