# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0031_auto_20180109_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
