# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0033_auto_20180121_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='200', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='width_field',
            field=models.PositiveIntegerField(blank=True, default='200', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
    ]
