# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0034_auto_20180121_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='image_width',
            new_name='height_field',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='url_height',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='url_width',
        ),
    ]
