# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkproj', '0038_auto_20180124_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
